# Generated by Django 5.0.3 on 2024-03-18 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
