# Generated by Django 5.0.3 on 2024-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_comment_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply_to",
        ),
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ManyToManyField(blank=True, null=True, to="web.comment"),
        ),
    ]
