# Generated by Django 5.0.3 on 2024-03-18 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_comment_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply_to",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="web.comment",
            ),
        ),
    ]
