# Generated by Django 5.0.3 on 2024-03-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_remove_comment_reply_to_comment_parent_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.place",
            ),
        ),
    ]
