# Generated by Django 5.0.3 on 2024-03-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="image",
            field=models.FileField(upload_to="customers/"),
        ),
    ]
