# Generated by Django 5.0.3 on 2024-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_customers_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="feature/", verbose_name="Image"),
                ),
                (
                    "icon",
                    models.FileField(upload_to="feature/icons", verbose_name="Icon"),
                ),
                (
                    "iconbackground",
                    models.CharField(max_length=50, verbose_name="Icon Background"),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "testinomialdescription",
                    models.TextField(verbose_name="Testimonail Description"),
                ),
                (
                    "testinomialauthor",
                    models.CharField(max_length=50, verbose_name="Description Author"),
                ),
                (
                    "authordesignation",
                    models.CharField(max_length=50, verbose_name="Author Designation"),
                ),
                (
                    "testinomialicon",
                    models.FileField(
                        upload_to="feature/testimonials",
                        verbose_name="Testimonail Icon",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
    ]
