# Generated by Django 5.0.3 on 2024-03-15 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_feature_rename_customers_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="authordesignation",
            new_name="author_designation",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="iconbackground",
            new_name="icon_background",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="testinomialauthor",
            new_name="testinomial_author",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="testinomialdescription",
            new_name="testinomial_description",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="testinomialicon",
            new_name="testinomial_icon",
        ),
    ]
