# Generated by Django 5.0.3 on 2024-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_rename_authordesignation_feature_author_designation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/", verbose_name="Image")),
                ("title", models.CharField(max_length=250)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog", "Blog Post"),
                            ("webinar", "Webinar"),
                            ("CN", "Report"),
                        ],
                        max_length=50,
                        verbose_name="Icon Background",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="marketing-feature/", verbose_name="Image"
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="product/", verbose_name="Image"),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.FileField(upload_to="product/icons", verbose_name="Icon"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="testimonial/", verbose_name="Image"),
                ),
                (
                    "icon",
                    models.FileField(
                        upload_to="testimonial/icons", verbose_name="Icon"
                    ),
                ),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=250)),
                (
                    "company_name",
                    models.CharField(max_length=50, verbose_name="Company Name"),
                ),
                (
                    "testinomial_description",
                    models.TextField(verbose_name="Testimonail Description"),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VideoBlogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="product/", verbose_name="Image"),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "icon",
                    models.FileField(upload_to="product/icons", verbose_name="Icon"),
                ),
            ],
        ),
    ]
