# Generated by Django 5.0.3 on 2024-03-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_videoblogs_icon_alter_videoblogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingfeature",
            name="image",
            field=models.FileField(
                upload_to="marketing-feature/", verbose_name="Image"
            ),
        ),
    ]
