# Generated by Django 5.0.3 on 2024-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_marketingfeature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog Post"),
                    ("webinar", "Webinar"),
                    ("CN", "Report"),
                ],
                max_length=50,
                verbose_name="Content Type",
            ),
        ),
    ]
