# Generated by Django 5.0.3 on 2024-03-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_blog_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonials",
            name="testinomial_description",
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="testimonial/icons",
                verbose_name="Icon",
            ),
        ),
    ]
