# Generated by Django 5.0.3 on 2024-03-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_remove_testimonials_testinomial_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonials",
            name="designation",
            field=models.CharField(
                default="abnc", max_length=250, verbose_name="Designation"
            ),
            preserve_default=False,
        ),
    ]
