# Generated by Django 5.0.3 on 2024-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_product_background_color_product_theme_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog Post"),
                    ("webinar", "Report"),
                    ("report", "Report"),
                ],
                max_length=50,
                verbose_name="Content Type",
            ),
        ),
    ]
