# Generated by Django 5.0.3 on 2024-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_alter_blog_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("Blog Post", "blog"),
                    ("Webinar", "webinar"),
                    ("Report", "report"),
                ],
                max_length=50,
                verbose_name="Content Type",
            ),
        ),
    ]
