# Generated by Django 5.0.3 on 2024-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todos",
            old_name="completed",
            new_name="isCompleted",
        ),
        migrations.AddField(
            model_name="todos",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
    ]
