# Generated by Django 5.0.3 on 2024-04-04 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentdetails",
            options={"verbose_name_plural": "Student Details"},
        ),
    ]
