# Generated by Django 5.0.3 on 2024-04-04 14:49

import auths.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0003_studentdetails_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default.webp",
                null=True,
                upload_to="images/",
                validators=[auths.validators.validate_file_extension],
            ),
        ),
    ]
